### ISSUE TITLE
Some vehicles missing/incorrect operating nation symbol

### ISSUE THREAD

**Issue by Theren03** [Addysaurus/lang_modding#2]
Some vehicles do not have a (correct) symbol indicating an operator country when they are not domestic vehicles.

Sweden
- Saab 105 Ö missing Austria symbol
- K9 (VIDAR) missing Norway symbol
France
- B-26 has regular roundel instead of Cross of Lorraine
Italy
- IAR-81C missing (Române) tag
- M60A1 Premium missing Italy roundel (If the M26 Premium has the roundel the M60 should too)
China
- Il-28 missing PRC symbol
- T-69 II G missing Bangladesh symbol (not sure what you'd use tho)
Great Britain
- Vijayanta missing India symbol
- Khalid missing Jordan symbol (not sure what you'd use tho)
Germany
- He 112 Premium missing (Române) tag
- Lim-5P missing Poland symbol
- Vilkas missing Lithuania symbol

I did not check boats, might do that later

**Comment by Addysaurus** [comment]
Roundels are used based on name. If a vehicle has the same name as the name the country that produced it gave it, it gets a roundel. Vijayanta is a unique name, so it does not get a tag. The same goes for the IAR-81C. That's the same reason that the Fokker G.I Mercury is not getting its roundel in my mod. I will reuse that roundel for the Austrian stuff because I have nothing better to use. T-69 II G is also not getting the bangladesh roundel, neither is Khalid getting a Jordanian one, and the Vilkas is not getting a Lithuanian one.

The Lim-5P doesn't get the Polish roundel because the one we have is East German, but I will give it the GDR roundel.

The K9 is not getting a roundel because I have nothing to use for one. Sorry. I want to give it one.

The Saab 105 Ö, French B-26C-15-MA, Italian M60A1, Chinese Il-28, Romanian premium He 112, and the Lim-5P will all be fixed. This has also reminded me to fix the Hungarian premium He 112 in the German tree because those tags are for when I don't have a roundel to use. It's going to get the chevron roundel that the late Hungarian stuff has because that chevron roundel was used pre-war and the Hungarian He 112 does have the chevron on it.

Thanks for the report! :)

**Comment by Theren03** [comment]
You could put the crown for the K9 like you did for the Norwegian leo 1a5

**Comment by Addysaurus** [comment]
Oh true I could. Thx for reminding me I did that.

**Comment by Addysaurus** [comment]
Ok actually I found a roundel that could work for Romania. It's not great, I don't like it, but it works.

**Comment by Addysaurus** [comment]
Fixed in 1.08.34, but the roundel for the Saab 105 Ö will just look like a blank square for a few days because that will only count as a new roundel when Seek and Destroy comes out in a few days.
